services:
  dextrading-api:
    container_name: dextrading-api
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - '${APP_PORT}:${APP_PORT}'
    networks:
      - dextrading-intranet
    env_file:
      - .env
    environment:
      - DB_HOST=dextrading-mysql
    depends_on:
      dextrading-mysql:
        condition: service_healthy
    command: node dist/main.js

  dextrading-mysql:
    container_name: dextrading-mysql
    restart: always
    image: mysql:8.0.29
    env_file: .env
    volumes:
      - mysql:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 3307:${DB_PORT}
    networks:
      - dextrading-intranet
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      TZ: 'utc'
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ['CMD', 'mysqladmin', '-u${DB_USER}', '-p${DB_PASSWORD}', 'ping']
      interval: 10s
      retries: 5
      timeout: 10s
      start_period: 15s

volumes:
  mysql:
    name: dextrading-mysql

networks:
  dextrading-intranet:
    name: dextrading-intranet
    driver: bridge
