services:
  my-system-api:
    container_name: my-system-api
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    ports:
      - '${APP_PORT}:${APP_PORT}'
    networks:
      - my-system-intranet
    env_file:
      - .env
    environment:
      - DB_HOST=my-system-mysql
    depends_on:
      my-system-mysql:
        condition: service_healthy
      my-system-redis:
        condition: service_healthy
    volumes:
      - ./uploads:/uploads
    healthcheck:
      test: [ 'CMD', 'curl', '-f', 'http://localhost:${APP_PORT}' ]
      interval: 30s
      timeout: 10s
      retries: 3
    command: node dist/main.js

  my-system-mysql:
    container_name: my-system-mysql
    restart: always
    image: mysql:8.0.29
    env_file: .env
    volumes:
      - mysql:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - '3308:${DB_PORT}'
    networks:
      - my-system-intranet
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      TZ: 'utc'
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test:
        [
          'CMD',
          'mysqladmin',
          '-u${DB_USER}',
          '-p${DB_PASSWORD}',
          'ping'
        ]
      interval: 10s
      retries: 5
      timeout: 10s
      start_period: 15s

  my-system-redis:
    container_name: my-system-redis
    image: redis:alpine
    restart: unless-stopped
    volumes:
      - redis:/data
    ports:
      - 6380:${REDIS_PORT}
    networks:
      - my-system-intranet
    healthcheck:
      test: [ 'CMD', 'redis-cli', 'ping' ]
      interval: 5s
      retries: 3
      timeout: 3s

  mysql-backup:
    container_name: mysql-backup
    image: databack/mysql-backup
    env_file: .env
    environment:
      DB_SERVER: my-system-mysql
      DB_PORT: ${DB_PORT}
      DB_USER: ${DB_USER}
      DB_PASS: ${DB_PASSWORD}
      BACKUP_DIR: '/backups'
    networks:
      - my-system-intranet
    volumes:
      - ./backups:/backups
    depends_on:
      - my-system-mysql

volumes:
  mysql:
    name: my-system-mysql
  redis:
    name: my-system-redis

networks:
  my-system-intranet:
    name: my-system-intranet
    driver: bridge
